CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Doctors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Specialty" text NOT NULL,
    "LicenseNumber" text NOT NULL,
    "Phone" text NOT NULL,
    "Email" text NOT NULL,
    "ConsultationFee" numeric NOT NULL,
    "ExperienceYears" integer NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id")
);

CREATE TABLE "Medicines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MedicineName" text NOT NULL,
    "GenericName" text NOT NULL,
    "Category" text NOT NULL,
    "DosageForm" text NOT NULL,
    "Strength" text NOT NULL,
    "PackSize" text NOT NULL,
    "Manufacturer" text NOT NULL,
    "Supplier" text NOT NULL,
    "Stock" integer NOT NULL,
    "ReorderLevel" integer NOT NULL,
    "Unit" text NOT NULL,
    "PurchasePrice" numeric NOT NULL,
    "SellingPrice" numeric NOT NULL,
    "GST" numeric NOT NULL,
    "MfgDate" timestamp with time zone,
    "ExpDate" timestamp with time zone,
    "Storage" text NOT NULL,
    "Usage" text NOT NULL,
    "SideEffects" text NOT NULL,
    "Instructions" text NOT NULL,
    "PrescriptionRequired" text NOT NULL,
    CONSTRAINT "PK_Medicines" PRIMARY KEY ("Id")
);

CREATE TABLE "Patients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    "Gender" text NOT NULL,
    "BloodGroup" text NOT NULL,
    "Phone" text NOT NULL,
    "Email" text NOT NULL,
    "Address" text NOT NULL,
    "MedicalHistory" text NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "Password" text NOT NULL,
    "Role" text NOT NULL,
    "Status" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Appointments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "AppointmentDate" timestamp with time zone NOT NULL,
    "TimeSlot" text NULL,
    "Status" text NULL,
    "Notes" text NULL,
    "Subject" text NULL,
    "TokenNumber" text NULL,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Prescriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AppointmentId" integer NOT NULL,
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "DateIssued" timestamp with time zone NOT NULL,
    "Diagnosis" text NOT NULL,
    "MedicineNotes" text NOT NULL,
    "AdditionalNotes" text NOT NULL,
    CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Prescriptions_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prescriptions_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Prescriptions_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");

CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");

CREATE INDEX "IX_Prescriptions_AppointmentId" ON "Prescriptions" ("AppointmentId");

CREATE INDEX "IX_Prescriptions_DoctorId" ON "Prescriptions" ("DoctorId");

CREATE INDEX "IX_Prescriptions_PatientId" ON "Prescriptions" ("PatientId");

CREATE TABLE "OPDSchedules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" integer NOT NULL,
    "DayOfWeek" text NOT NULL,
    "StartTime" text NOT NULL,
    "EndTime" text NOT NULL,
    "MaxPatients" integer NOT NULL,
    "RoomNumber" text NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_OPDSchedules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OPDSchedules_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Feedbacks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PatientId" integer NULL,
    "PatientName" text NULL,
    "Rating" integer NOT NULL,
    "Comment" text NOT NULL,
    "SubmittedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "IsVisible" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Feedbacks_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE SET NULL
);

CREATE INDEX "IX_OPDSchedules_DoctorId" ON "OPDSchedules" ("DoctorId");
CREATE INDEX "IX_Feedbacks_PatientId" ON "Feedbacks" ("PatientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260406075440_InitialCreateToPostgres', '8.0.2');

COMMIT;

